### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by mooseyboots** [40ants/scrapycl#4]
i have latest quicklisp and ultralisp, i'm using sly as my REPL and SBCL.

when i try to install using `(ql:quickload :scrapycl)` i get the following error:

```
The value of uiop/package::from-package is nil, which is not of type package.
```

it's caused by compiling file `scrapycl/spider.lisp`.

do you have any ideas what might be wrong? i looked at that file and it just defines a package and a class.

**Comment by svetlyak40wt** [comment]
Interesting, which version of bordeaux-threads do you have?

In asd file I tell ASDF there is a bt2 package inside of it:
https://github.com/40ants/scrapycl/blob/master/scrapycl.asd#L24

I've updated all dists now and can't reproduce the problem. Here is versions of the libraryes I'm have:

```
CL-USER> (ql:where-is-system :scrapycl)
#P"/Users/art/.roswell/lisp/quicklisp/dists/ultralisp/software/40ants-scrapycl-20240318203523/"
CL-USER> (ql:where-is-system :bordeaux-threads)
#P"/Users/art/.roswell/lisp/quicklisp/dists/ultralisp/software/sionescu-bordeaux-threads-20240716130121/"
```

What are your versions?

**Comment by svetlyak40wt** [comment]
In the latest bordeax-threads it has this package:

https://github.com/sionescu/bordeaux-threads/blob/master/apiv2/pkgdcl.lisp#L4

**Comment by mooseyboots** [comment]
thanks for the pointer, i had to update that system.

i'm very well-versed in knowing how to wrangle versions, and just quickloading :bordeaux-threads would not impose a newer version.

manually removing my old version and re-installing fixed it. thanks!
